/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Pepipost;
using Pepipost.Utilities;

namespace Pepipost.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum AggregatedByEnum
    {
        DAY, //TODO: Write general description for this method
        WEEK, //TODO: Write general description for this method
        MONTH, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type AggregatedByEnum
    /// </summary>
    public static class AggregatedByEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "day", "week", "month" };

        /// <summary>
        /// Converts a AggregatedByEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The AggregatedByEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(AggregatedByEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case AggregatedByEnum.DAY:
                case AggregatedByEnum.WEEK:
                case AggregatedByEnum.MONTH:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of AggregatedByEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of AggregatedByEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<AggregatedByEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into AggregatedByEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed AggregatedByEnum value</returns>
        public static AggregatedByEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type AggregatedByEnum", value));

            return (AggregatedByEnum) index;
        }
    }
} 