/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using Pepipost.Utilities;

namespace Pepipost.Models
{
    public class Attributes
    {
        private string attributes;
        public Attributes(string attributes)
        {
            this.attributes = attributes;
        }
        // These fields hold the values for the public properties.

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        public Object GetAttributes()
        {
            return APIHelper.JsonDeserialize<Object>(this.attributes);
        }
    }
}