/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Pepipost;
using Pepipost.Utilities;


namespace Pepipost.Models
{
    public class CreateSubaccount : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string username;
        private string email;
        private string setpassword;
        private string password;
        private string creditType;

        /// <summary>
        /// provide a username for the subaccount
        /// </summary>
        [JsonProperty("username")]
        public string Username 
        { 
            get 
            {
                return this.username; 
            } 
            set 
            {
                this.username = value;
                onPropertyChanged("Username");
            }
        }

        /// <summary>
        /// email address to be registered with the account.
        /// </summary>
        [JsonProperty("email")]
        public string Email 
        { 
            get 
            {
                return this.email; 
            } 
            set 
            {
                this.email = value;
                onPropertyChanged("Email");
            }
        }

        /// <summary>
        /// You can opt to set the password for the subaccount.\nIf set as 1, please provide a value in password parameter.\nIf set as 0, the email confirmation link will act as a password reset link.
        /// </summary>
        [JsonProperty("setpassword")]
        public string Setpassword 
        { 
            get 
            {
                return this.setpassword; 
            } 
            set 
            {
                this.setpassword = value;
                onPropertyChanged("Setpassword");
            }
        }

        /// <summary>
        /// It is required to pass this value, if setpassword is set as 1.\nThe password must comprise minimum of 8 characters and include one uppercase character, one lowercase character, one numeric character.
        /// </summary>
        [JsonProperty("password")]
        public string Password 
        { 
            get 
            {
                return this.password; 
            } 
            set 
            {
                this.password = value;
                onPropertyChanged("Password");
            }
        }

        /// <summary>
        /// Allowed values one_time_credit or unlimited by default, all subaccounts are created with credit type as unlimited.
        /// </summary>
        [JsonProperty("credit_type")]
        public string CreditType 
        { 
            get 
            {
                return this.creditType; 
            } 
            set 
            {
                this.creditType = value;
                onPropertyChanged("CreditType");
            }
        }
    }
} 