/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Pepipost;
using Pepipost.Utilities;


namespace Pepipost.Models
{
    public class From : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string fromEmail;
        private string fromName;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fromEmail")]
        public string FromEmail 
        { 
            get 
            {
                return this.fromEmail; 
            } 
            set 
            {
                this.fromEmail = value;
                onPropertyChanged("FromEmail");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fromName")]
        public string FromName 
        { 
            get 
            {
                return this.fromName; 
            } 
            set 
            {
                this.fromName = value;
                onPropertyChanged("FromName");
            }
        }
    }
} 