/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Pepipost;
using Pepipost.Utilities;


namespace Pepipost.Models
{
    public class Personalizations : BaseModel 
    {
        // These fields hold the values for the public properties.
        private object attributes;
        private object headers;
        private List<Models.Attachments> attachments;
        private List<Models.EmailStruct> to;
        private List<Models.EmailStruct> cc;
        private List<Models.EmailStruct> bcc;
        private string tokenTo;
        private string tokenCc;
        private string tokenBcc;

        /// <summary>
        /// Dynamic attributes
        /// </summary>
        [JsonProperty("attributes")]
        public object Attributes 
        { 
            get 
            {
                return this.attributes; 
            } 
            set 
            {
                this.attributes = value;
                onPropertyChanged("Attributes");
            }
        }

        /// <summary>
        /// Dynamic headers attributes
        /// </summary>
        [JsonProperty("headers")]
        public object Headers 
        { 
            get 
            {
                return this.headers; 
            } 
            set 
            {
                this.headers = value;
                onPropertyChanged("Headers");
            }
        }

        /// <summary>
        /// Attachments to individuals recipient
        /// </summary>
        [JsonProperty("attachments")]
        public List<Models.Attachments> Attachments 
        { 
            get 
            {
                return this.attachments; 
            } 
            set 
            {
                this.attachments = value;
                onPropertyChanged("Attachments");
            }
        }

        /// <summary>
        /// To email-address
        /// </summary>
        [JsonProperty("to")]
        public List<Models.EmailStruct> To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// CC email-address
        /// </summary>
        [JsonProperty("cc")]
        public List<Models.EmailStruct> Cc 
        { 
            get 
            {
                return this.cc; 
            } 
            set 
            {
                this.cc = value;
                onPropertyChanged("Cc");
            }
        }

        /// <summary>
        /// Bcc email-addresses
        /// </summary>
        [JsonProperty("bcc")]
        public List<Models.EmailStruct> Bcc 
        { 
            get 
            {
                return this.bcc; 
            } 
            set 
            {
                this.bcc = value;
                onPropertyChanged("Bcc");
            }
        }

        /// <summary>
        /// token to which is json string
        /// </summary>
        [JsonProperty("token_to")]
        public string TokenTo 
        { 
            get 
            {
                return this.tokenTo; 
            } 
            set 
            {
                this.tokenTo = value;
                onPropertyChanged("TokenTo");
            }
        }

        /// <summary>
        /// token cc which is json string
        /// </summary>
        [JsonProperty("token_cc")]
        public string TokenCc 
        { 
            get 
            {
                return this.tokenCc; 
            } 
            set 
            {
                this.tokenCc = value;
                onPropertyChanged("TokenCc");
            }
        }

        /// <summary>
        /// token bcc which is json string
        /// </summary>
        [JsonProperty("token_bcc")]
        public string TokenBcc 
        { 
            get 
            {
                return this.tokenBcc; 
            } 
            set 
            {
                this.tokenBcc = value;
                onPropertyChanged("TokenBcc");
            }
        }
    }
} 