/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Pepipost;
using Pepipost.Utilities;


namespace Pepipost.Models
{
    public class SendEmailError : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string errorMessage;
        private int errorCode;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("error_message")]
        public string ErrorMessage 
        { 
            get 
            {
                return this.errorMessage; 
            } 
            set 
            {
                this.errorMessage = value;
                onPropertyChanged("ErrorMessage");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("error_code")]
        public int ErrorCode 
        { 
            get 
            {
                return this.errorCode; 
            } 
            set 
            {
                this.errorCode = value;
                onPropertyChanged("ErrorCode");
            }
        }
    }
} 