/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Pepipost;
using Pepipost.Utilities;


namespace Pepipost.Models
{
    public class Settings : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool? footer;
        private bool? clickTrack;
        private bool? openTrack;
        private bool? unsubscribeTrack;
        private bool? hepf;

        /// <summary>
        /// enable or disable footer
        /// </summary>
        [JsonProperty("footer")]
        public bool? Footer 
        { 
            get 
            {
                return this.footer; 
            } 
            set 
            {
                this.footer = value;
                onPropertyChanged("Footer");
            }
        }

        /// <summary>
        /// enable or disable click tracking
        /// </summary>
        [JsonProperty("click_track")]
        public bool? ClickTrack 
        { 
            get 
            {
                return this.clickTrack; 
            } 
            set 
            {
                this.clickTrack = value;
                onPropertyChanged("ClickTrack");
            }
        }

        /// <summary>
        /// enable or disable open tracking
        /// </summary>
        [JsonProperty("open_track")]
        public bool? OpenTrack 
        { 
            get 
            {
                return this.openTrack; 
            } 
            set 
            {
                this.openTrack = value;
                onPropertyChanged("OpenTrack");
            }
        }

        /// <summary>
        /// enable or disable unsubscribe tracking
        /// </summary>
        [JsonProperty("unsubscribe_track")]
        public bool? UnsubscribeTrack 
        { 
            get 
            {
                return this.unsubscribeTrack; 
            } 
            set 
            {
                this.unsubscribeTrack = value;
                onPropertyChanged("UnsubscribeTrack");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("hepf")]
        public bool? Hepf 
        { 
            get 
            {
                return this.hepf; 
            } 
            set 
            {
                this.hepf = value;
                onPropertyChanged("Hepf");
            }
        }
    }
} 