/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Linq;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Pepipost;
using Pepipost.Utilities;

namespace Pepipost.Models
{
    [JsonConverter(typeof(StringValuedEnumConverter))]
    public enum SortEnum
    {
        ASC, //TODO: Write general description for this method
        DESC, //TODO: Write general description for this method
    }

    /// <summary>
    /// Helper for the enum type SortEnum
    /// </summary>
    public static class SortEnumHelper
    {
        //string values corresponding the enum elements
        private static List<string> stringValues = new List<string> { "asc", "desc" };

        /// <summary>
        /// Converts a SortEnum value to a corresponding string value
        /// </summary>
        /// <param name="enumValue">The SortEnum value to convert</param>
        /// <returns>The representative string value</returns>
        public static string ToValue(SortEnum enumValue)
        {
            switch(enumValue)
            {
                //only valid enum elements can be used
                //this is necessary to avoid errors
                case SortEnum.ASC:
                case SortEnum.DESC:
                    return stringValues[(int)enumValue];

                //an invalid enum value was requested
                default:
                    return null;
            }
        }

        /// <summary>
        /// Convert a list of SortEnum values to a list of strings
        /// </summary>
        /// <param name="enumValues">The list of SortEnum values to convert</param>
        /// <returns>The list of representative string values</returns>
        public static List<string> ToValue(List<SortEnum> enumValues)
        {
            if (null == enumValues)
                return null;

            return enumValues.Select(eVal => ToValue(eVal)).ToList();
        }

        /// <summary>
        /// Converts a string value into SortEnum value
        /// </summary>
        /// <param name="value">The string value to parse</param>
        /// <returns>The parsed SortEnum value</returns>
        public static SortEnum ParseString(string value)
        {
            int index = stringValues.IndexOf(value);
            if(index < 0)
                throw new InvalidCastException(string.Format("Unable to cast value: {0} to type SortEnum", value));

            return (SortEnum) index;
        }
    }
} 