/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Pepipost;
using Pepipost.Utilities;


namespace Pepipost.Models
{
    public class UpdateCredisOfSubaccount : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string username;
        private Models.ActionEnum? action;
        private int? amount;

        /// <summary>
        /// The username of the subaccount
        /// </summary>
        [JsonProperty("username")]
        public string Username 
        { 
            get 
            {
                return this.username; 
            } 
            set 
            {
                this.username = value;
                onPropertyChanged("Username");
            }
        }

        /// <summary>
        /// Indicate the action (add or subtract) to be taken.Allowed values increase, decrease
        /// </summary>
        [JsonProperty("action", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.ActionEnum? Action 
        { 
            get 
            {
                return this.action; 
            } 
            set 
            {
                this.action = value;
                onPropertyChanged("Action");
            }
        }

        /// <summary>
        /// Amount of credits
        /// </summary>
        [JsonProperty("amount")]
        public int? Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }
    }
} 