/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Pepipost;
using Pepipost.Utilities;


namespace Pepipost.Models
{
    public class UpdateRecurringCredisOfSubaccount : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string username;
        private int? recurringCredit;
        private Models.TimeperiodEnum? timeperiod;
        private string startDate;
        private string endDate;
        private string status;

        /// <summary>
        /// The username of the subaccount
        /// </summary>
        [JsonProperty("username")]
        public string Username 
        { 
            get 
            {
                return this.username; 
            } 
            set 
            {
                this.username = value;
                onPropertyChanged("Username");
            }
        }

        /// <summary>
        /// The amount to be added periodically
        /// </summary>
        [JsonProperty("recurring_credit")]
        public int? RecurringCredit 
        { 
            get 
            {
                return this.recurringCredit; 
            } 
            set 
            {
                this.recurringCredit = value;
                onPropertyChanged("RecurringCredit");
            }
        }

        /// <summary>
        /// The periodic \n\nAllowed values  \"daily\", \"weekly\", \"monhtly\"
        /// </summary>
        [JsonProperty("timeperiod", ItemConverterType = typeof(StringValuedEnumConverter))]
        public Models.TimeperiodEnum? Timeperiod 
        { 
            get 
            {
                return this.timeperiod; 
            } 
            set 
            {
                this.timeperiod = value;
                onPropertyChanged("Timeperiod");
            }
        }

        /// <summary>
        /// The date from which the credit allocation will commence
        /// </summary>
        [JsonProperty("start_date")]
        public string StartDate 
        { 
            get 
            {
                return this.startDate; 
            } 
            set 
            {
                this.startDate = value;
                onPropertyChanged("StartDate");
            }
        }

        /// <summary>
        /// The last date of credit allocation
        /// </summary>
        [JsonProperty("end_date")]
        public string EndDate 
        { 
            get 
            {
                return this.endDate; 
            } 
            set 
            {
                this.endDate = value;
                onPropertyChanged("EndDate");
            }
        }

        /// <summary>
        /// Flag to enable or disable the recurring credit allocation
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }
    }
} 