/*
 * PepipostAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PepipostAPI.Standard;
using PepipostAPI.Standard.Utilities;


namespace PepipostAPI.Standard.Models
{
    public class Attribute : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string myname;
        private string age;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("myname")]
        public string Myname 
        { 
            get 
            {
                return this.myname; 
            } 
            set 
            {
                this.myname = value;
                onPropertyChanged("Myname");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("age")]
        public string Age 
        { 
            get 
            {
                return this.age; 
            } 
            set 
            {
                this.age = value;
                onPropertyChanged("Age");
            }
        }
    }
} 