/*
 * PepipostAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PepipostAPI.Standard;
using PepipostAPI.Standard.Utilities;


namespace PepipostAPI.Standard.Models
{
    public class Settings : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? footer;
        private int? clicktrack;
        private int? opentrack;
        private int? unsubscribe;
        private string bcc;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("footer")]
        public int? Footer 
        { 
            get 
            {
                return this.footer; 
            } 
            set 
            {
                this.footer = value;
                onPropertyChanged("Footer");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("clicktrack")]
        public int? Clicktrack 
        { 
            get 
            {
                return this.clicktrack; 
            } 
            set 
            {
                this.clicktrack = value;
                onPropertyChanged("Clicktrack");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("opentrack")]
        public int? Opentrack 
        { 
            get 
            {
                return this.opentrack; 
            } 
            set 
            {
                this.opentrack = value;
                onPropertyChanged("Opentrack");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("unsubscribe")]
        public int? Unsubscribe 
        { 
            get 
            {
                return this.unsubscribe; 
            } 
            set 
            {
                this.unsubscribe = value;
                onPropertyChanged("Unsubscribe");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bcc")]
        public string Bcc 
        { 
            get 
            {
                return this.bcc; 
            } 
            set 
            {
                this.bcc = value;
                onPropertyChanged("Bcc");
            }
        }
    }
} 