/*
 * Pepipost
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using Pepipost.Controllers;
using Pepipost.Http.Client;
using Pepipost.Utilities;

namespace Pepipost
{
    public partial class PepipostClient
    {

        /// <summary>
        /// Singleton access to MailSend controller
        /// </summary>
        public MailSendController MailSend
        {
            get
            {
                return MailSendController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Events controller
        /// </summary>
        public EventsController Events
        {
            get
            {
                return EventsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Stats controller
        /// </summary>
        public StatsController Stats
        {
            get
            {
                return StatsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Subaccounts controller
        /// </summary>
        public SubaccountsController Subaccounts
        {
            get
            {
                return SubaccountsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SubaccountsDelete controller
        /// </summary>
        public SubaccountsDeleteController SubaccountsDelete
        {
            get
            {
                return SubaccountsDeleteController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SubaccountsGetSubAccounts controller
        /// </summary>
        public SubaccountsGetSubAccountsController SubaccountsGetSubAccounts
        {
            get
            {
                return SubaccountsGetSubAccountsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Setrecurringcreditddetails controller
        /// </summary>
        public SetrecurringcreditddetailsController Setrecurringcreditddetails
        {
            get
            {
                return SetrecurringcreditddetailsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SubaccountsSetsubaccountcredit controller
        /// </summary>
        public SubaccountsSetsubaccountcreditController SubaccountsSetsubaccountcredit
        {
            get
            {
                return SubaccountsSetsubaccountcreditController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SubaccountsUpdateSubaccount controller
        /// </summary>
        public SubaccountsUpdateSubaccountController SubaccountsUpdateSubaccount
        {
            get
            {
                return SubaccountsUpdateSubaccountController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to SubaccountsCreateSubaccount controller
        /// </summary>
        public SubaccountsCreateSubaccountController SubaccountsCreateSubaccount
        {
            get
            {
                return SubaccountsCreateSubaccountController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Suppression controller
        /// </summary>
        public SuppressionController Suppression
        {
            get
            {
                return SuppressionController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to DomainDelete controller
        /// </summary>
        public DomainDeleteController DomainDelete
        {
            get
            {
                return DomainDeleteController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Domain controller
        /// </summary>
        public DomainController Domain
        {
            get
            {
                return DomainController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public PepipostClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public PepipostClient(string apiKey)
        {
            Configuration.ApiKey = apiKey;
        }
        #endregion
    }
}