/*
 * PepipostAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using PepipostAPI.Standard.Controllers;
using PepipostAPI.Standard.Http.Client;
using PepipostAPI.Standard.Utilities;

namespace PepipostAPI.Standard
{
    public partial class PepipostAPIClient
    {

        /// <summary>
        /// Singleton access to Email controller
        /// </summary>
        public EmailController Email
        {
            get
            {
                return EmailController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public PepipostAPIClient() { }
        #endregion
    }
}